import { Redirect } from 'expo-router';
import { useState } from 'react';
import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, SafeAreaView, StyleSheet, Text, TextInput, View } from 'react-native';
import { AppColors } from '@/constants/app';
import { useAuth } from '@/lib/auth';

export default function SignInScreen() {
  const { user, loading, requestCode, verifyCode } = useAuth();
  const [email, setEmail] = useState(''); const [code, setCode] = useState(''); const [step, setStep] = useState<'email' | 'code'>('email'); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  if (user) return <Redirect href="/(tabs)" />;
  if (loading) return <View style={styles.loading}><ActivityIndicator size="large" color={AppColors.blue} /></View>;
  async function submit() { setBusy(true); setMessage(''); try { if (step === 'email') { await requestCode(email); setStep('code'); setMessage('メールに届いた6桁を入力してください。'); } else { await verifyCode(email, code); } } catch (error) { setMessage(error instanceof Error ? error.message : '処理できませんでした。'); } finally { setBusy(false); } }
  return <SafeAreaView style={styles.safe}><KeyboardAvoidingView style={styles.page} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><View style={styles.brand}><View style={styles.mark}><Text style={styles.markText}>G</Text></View><Text style={styles.brandName}>GIVE HUB</Text></View><View style={styles.copy}><Text style={styles.eyebrow}>MEMBERS ONLY</Text><Text style={styles.title}>仲間のつながりから、{`\n`}信頼できる人と出会う。</Text><Text style={styles.lead}>守成クラブ会員向けの紹介・探しごとアプリです。登録済みの会員情報を確認するため、メール認証が必要です。</Text></View><View style={styles.card}><Text style={styles.label}>{step === 'email' ? 'メールアドレス' : '6桁の認証コード'}</Text>{step === 'email' ? <TextInput style={styles.input} value={email} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none" autoComplete="email" placeholder="you@example.com" /> : <TextInput style={[styles.input, styles.code]} value={code} onChangeText={(value) => setCode(value.replace(/\D/g, '').slice(0, 6))} keyboardType="number-pad" autoComplete="one-time-code" placeholder="000000" maxLength={6} />} {!!message && <Text style={styles.message}>{message}</Text>}<Pressable style={[styles.button, busy && styles.disabled]} onPress={submit} disabled={busy}><Text style={styles.buttonText}>{busy ? '処理中…' : step === 'email' ? '認証コードを送る' : 'ログインする'}</Text></Pressable>{step === 'code' && <Pressable onPress={() => { setStep('email'); setCode(''); setMessage(''); }}><Text style={styles.back}>メールアドレスを変更</Text></Pressable>}</View><Text style={styles.note}>登録済み会員専用</Text></KeyboardAvoidingView></SafeAreaView>;
}

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: AppColors.paper }, page: { flex: 1, padding: 22, justifyContent: 'center', gap: 26 }, loading: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: AppColors.paper }, brand: { flexDirection: 'row', alignItems: 'center', gap: 10 }, mark: { width: 42, height: 42, borderRadius: 13, alignItems: 'center', justifyContent: 'center', backgroundColor: AppColors.blue }, markText: { color: '#fff', fontSize: 21, fontWeight: '900' }, brandName: { color: AppColors.ink, fontSize: 19, fontWeight: '900', letterSpacing: 1 }, copy: { gap: 11 }, eyebrow: { color: AppColors.blue, fontSize: 12, fontWeight: '900', letterSpacing: 1.6 }, title: { color: AppColors.ink, fontSize: 30, lineHeight: 42, fontWeight: '900' }, lead: { color: AppColors.muted, fontSize: 14, lineHeight: 23, fontWeight: '700' }, card: { padding: 18, gap: 12, borderWidth: 1, borderColor: AppColors.line, borderRadius: 20, backgroundColor: '#fff' }, label: { color: '#30425F', fontSize: 14, fontWeight: '900' }, input: { minHeight: 54, paddingHorizontal: 14, borderWidth: 1, borderColor: '#CBD7E7', borderRadius: 12, backgroundColor: '#FAFCFF', color: AppColors.ink, fontSize: 16, fontWeight: '700' }, code: { textAlign: 'center', fontSize: 24, letterSpacing: 9 }, message: { color: AppColors.blueDark, fontSize: 12, lineHeight: 19, fontWeight: '800' }, button: { minHeight: 56, alignItems: 'center', justifyContent: 'center', borderRadius: 13, backgroundColor: AppColors.blue }, disabled: { opacity: .55 }, buttonText: { color: '#fff', fontSize: 16, fontWeight: '900' }, back: { paddingTop: 3, color: AppColors.blue, fontSize: 13, fontWeight: '900', textAlign: 'center' }, note: { color: '#8491A4', fontSize: 11, fontWeight: '700', textAlign: 'center' } });
