import {env} from 'cloudflare:workers';
import {setTestAccess} from './fixtures/meeting-platform-auth';
import {GET,POST} from '../app/api/admin/meetings/route';
import {GET as venueGet,POST as venuePost} from '../app/api/admin/meeting-venues/route';
import {GET as autoGet,POST as autoPost} from '../app/api/admin/meetings/automation/route';
import {getAdmin} from '../app/admin-auth';
import {createMeeting,meeting,importRoster,roster,submitAnswer,attendees,adminMeetingSummaries,checkSubmissionLimit} from '../db/meetings';
import {saveMeetingVenue,setMeetingOperator,canManageMeetingVenue} from '../db/meeting-venues';
import {setQrTableCount,qrTableCount,saveAutomation,automationStatus,syncSchedule,prepareScheduled,runMeetingAutomation} from '../db/meeting-automation';
import {managementTest} from '../scripts/meeting-tests/management';
import {matchAttendee} from '../app/meeting/matching';
import {person} from '../scripts/meeting-tests/fixtures';
export default {async fetch(){try{
 const checks:string[]=[];const ok=(v:unknown,name:string)=>{if(!v)throw new Error(name);checks.push(name);};
 async function request(kind:'meetings'|'venues'|'automation',email:string|null,body?:Record<string,unknown>,query='',origin='https://test.example.com'){setTestAccess(email);const r=new Request('https://test.example.com/api'+query,{method:body?'POST':'GET',headers:body?{origin,'content-type':'application/json'}:{},body:body?JSON.stringify(body):undefined});return body?({meetings:POST,venues:venuePost,automation:autoPost}[kind])(r):({meetings:GET,venues:venueGet,automation:autoGet}[kind])(r);}
 const own=await createMeeting({title:'Hiru fixture',venue:'ひるのめぐろ',closesAt:Date.now()+600000});
 const venue=await saveMeetingVenue({name:'別会場',website:'https://fixture.example.com/other',legacySlug:'other',startTime:'18:00'});
 const other=await createMeeting({title:'Other fixture',venue:'別会場',closesAt:Date.now()+600000},venue);
 await setMeetingOperator(venue,'operator@example.com',true);
 ok((await request('meetings',null)).status===403,'anonymous cannot administer');
 ok((await request('meetings','stranger@example.com')).status===403,'ordinary account cannot administer');
 const visible=await(await request('meetings','operator@example.com')).json() as {events:{id:string}[]};ok(visible.events.length===1&&visible.events[0].id===other,'operator lists only assigned venue');
 ok((await request('meetings','operator@example.com',undefined,'?id='+own)).status===403,'foreign event details denied');
 ok((await request('meetings','operator@example.com',undefined,'?venue=hirunomeguro')).status===403,'foreign venue list denied');
 for(const action of ['update','delete','deadline','qr-tables','import','attendance','analyze','remove','publish'])ok((await request('meetings','operator@example.com',{action,id:own,confirmation:'Hiru fixture',title:'Changed',venue:'Changed',closesAt:Date.now()+600000,tables:2,people:[person('x')],consent:true,personId:'x',present:true,candidateId:'x'})).status===403,'foreign mutation denied: '+action);
 ok((await request('meetings','operator@example.com',{action:'create',venueId:'hirunomeguro',title:'x',venue:'x',closesAt:Date.now()+600000})).status===403,'foreign event creation denied');
 ok((await request('meetings','operator@example.com',{action:'update',id:other,title:'更新',venue:'別会場'})).status===200,'assigned event editable');
 ok((await meeting(own))?.title==='Hiru fixture','foreign event unchanged');
 ok((await request('meetings','operator@example.com',{action:'update',id:other,title:'不正',venue:'別会場'},'', 'https://evil.example.com')).status===403,'cross origin rejected');
 ok((await request('venues','operator@example.com',{action:'save',name:'unauthorized'})).status===403,'operator cannot provision or grant access');
 ok((await request('venues','operator@example.com',{action:'operator',id:venue,email:'evil@example.com',enabled:true})).status===403,'operator cannot escalate privileges');
 const scoped=await(await request('venues','operator@example.com')).json() as {venues:{id:string}[];operators:unknown[]};ok(scoped.venues.length===1&&scoped.venues[0].id===venue,'venue settings scoped');
 setTestAccess('operator@example.com');ok(!await getAdmin(),'venue operator is not TASUKI platform admin');
 ok(!await canManageMeetingVenue('operator@example.com','hirunomeguro'),'QR authorization uses assigned venue');
 ok((await request('automation','operator@example.com',undefined,'?venue=hirunomeguro')).status===403,'foreign connection and schedule denied');
 ok((await request('automation','operator@example.com',{action:'save',venueId:'hirunomeguro',enabled:false})).status===403,'foreign automation mutation denied');
 ok((await request('automation','operator@example.com',undefined,'?venue='+venue)).status===403,'external venue has no automation connection UI/API');
 for(const email of ['operator@example.com','platform@example.com'])for(const action of ['save','sync','prepare'])ok((await request('automation',email,{action,venueId:venue,key:venue+':11636',loginUrl:'https://www.shuseiclub.jp/other/___STAFF___/onetime.php?id=test'})).status===403,'external automation denied: '+email+' '+action);
 for(const action of [()=>saveAutomation({enabled:true},venue),()=>syncSchedule(Date.now(),venue),()=>prepareScheduled(venue+':11636',true,Date.now(),venue)]){let blocked=false;try{await action();}catch{blocked=true;}ok(blocked,'external direct automation call blocked');}
 await automationStatus(venue);await env.DB.prepare('UPDATE meeting_venue_automation SET enabled=1 WHERE venue_id=?').bind(venue).run();await runMeetingAutomation(Date.parse('2026-10-05T01:00:00+09:00'));ok(!(await automationStatus(venue)).plans.length,'scheduler ignores external venue even with stale enabled setting');
 const uploaded=await request('meetings','operator@example.com',{action:'import',id:other,people:[{...person('upload'),name:'アップロード参加者',company:'会場会社',services:'名簿原文のPR',table:''}],consent:true});ok(uploaded.status===200&&(await roster(other))[0].services==='名簿原文のPR','external operator imports roster with original business description');
 await setMeetingOperator(venue,'operator@example.com',false);ok((await request('meetings','operator@example.com')).status===403,'revocation effective on next request');
 await setMeetingOperator(venue,'operator@example.com',true);setTestAccess('operator@example.com','suspended');ok((await GET(new Request('https://test.example.com/api'))).status===403,'suspended operator denied');
 ok((await request('meetings','platform@example.com',undefined,'?venue=hirunomeguro')).status===200,'platform admin retains access');
 const rosterProfiles=Array.from({length:200},(_,i)=>({...person('p'+i),name:'参加者'+i,company:'会社'+i,table:''}));await importRoster(own,rosterProfiles,true);ok((await roster(own)).length===200,'200 attendee roster accepted');
 const people=await roster(own);for(const p of people){const token=crypto.randomUUID().replaceAll('-','').repeat(2);await submitAnswer(own,{token,rosterId:p.id,need:'印刷',consent:true});}ok((await attendees(own)).length===200,'200 responses accepted including former 100 limit');
 await env.DB.prepare('UPDATE meeting_answers SET present=1,analyzed=1,candidates=\'[]\' WHERE event_id=?').bind(own).run();const a=(await attendees(own))[0];await env.DB.prepare('UPDATE meeting_answers SET candidates=? WHERE id=?').bind(JSON.stringify([{id:'fixture'}]),a.id).run();const metrics=(await adminMeetingSummaries('hirunomeguro')).find(e=>e.id===own);ok(metrics?.answerCount===200&&metrics.needCount===200&&metrics.matchedCount===1,'event counts use actual answers and match coverage');
 let over=false;try{await importRoster(other,Array.from({length:301},(_,i)=>({...person('x'),name:'n'+i,company:'c'+i})),true);}catch{over=true;}ok(over,'over 300 roster rejected');
 for(let i=0;i<600;i++)ok(await checkSubmissionLimit(own,'shared-wifi','read'),'shared Wi-Fi read '+i);
 const candidates=Array.from({length:200},(_,i)=>person('large-'+i,{industry:i===199?'印刷':'建築',services:i===199?'チラシ印刷':'内装工事'}));const matches=await matchAttendee({async run(){return {response:{matches:[]}};}},person('requester',{need:'印刷'}),candidates);ok(matches.some(c=>c.id==='large-199'),'matching can reach the last person of a 200 attendee list');
 await env.DB.prepare('UPDATE meeting_submit_limits SET count=12000').run();ok(await checkSubmissionLimit(own,'shared-wifi','read'),'200 attendees polling every 15 seconds retain Wi-Fi headroom');await env.DB.prepare('UPDATE meeting_submit_limits SET count=18000').run();ok(!await checkSubmissionLimit(own,'shared-wifi','read'),'Wi-Fi read limit remains bounded');await setQrTableCount(other,40);ok(await qrTableCount(other)===40,'large venue supports more than 26 QR tables');
 const management=await managementTest();checks.push(...management.checks);
 return Response.json({pass:true,checks:checks.filter(c=>!c.startsWith('shared Wi-Fi read')),wifiReads:600});
 }catch(e){return Response.json({error:String(e),stack:e instanceof Error?e.stack:''},{status:500});}}};
