 'use client';
import {useEffect,useState} from 'react';
import {GoogleMark} from '@/app/login/LoginForm';
export default function RegisterForm({invite}:{invite:string}){
 const [profile,setProfile]=useState({name:'',company:'',industry:'',services:'',area:''}),[email,setEmail]=useState(''),[code,setCode]=useState(''),[consent,setConsent]=useState(false),[sent,setSent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(new URLSearchParams(window.location.search).has('login'))setError('認証できませんでした。入力内容を確認して、もう一度お進みください。');},[]);
 async function post(action:string){const r=await fetch('/api/register',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,profile,email,code,consent,invite})}),d=await r.json() as {draft?:string;error?:string};if(!r.ok)throw new Error(d.error||'登録できませんでした。');return d;}
 async function go(action:string){setBusy(true);setError('');try{if(action==='google'){const d=await post('draft');window.location.href=`/api/auth/google/start?signup=1&draft=${encodeURIComponent(d.draft||'')}`;}else{await post(action);if(action==='request')setSent(true);else window.location.href='/register/complete';}}catch(e){setError(e instanceof Error?e.message:'通信できませんでした。');}finally{setBusy(false);}}
 return <main className="meeting-page meeting-survey meeting-signup tasuki-signup"><header className="meeting-hiru-brand"><strong>TASUKI</strong><small>仕事でつながる会員サービス</small></header><h1>あなたの得意を、<br/>次の仕事へ。</h1><section className="meeting-signup-form"><h2>無料アカウントを作成</h2><fieldset disabled={busy||sent} className="meeting-registration-profile">{([['name','お名前'],['company','会社名・屋号'],['industry','業種']] as const).map(([key,label])=><label key={key}>{label}<input value={profile[key]} maxLength={120} onChange={e=>setProfile({...profile,[key]:e.target.value})}/></label>)}<label>できる仕事・事業内容<textarea rows={2} maxLength={500} value={profile.services} placeholder="例：チラシのデザイン・印刷" onChange={e=>setProfile({...profile,services:e.target.value})}/></label><label className="meeting-consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span><a href="/terms" target="_blank">利用規約</a>・<a href="/privacy" target="_blank">プライバシーポリシー</a>に同意して登録します。</span></label></fieldset>{error&&<p role="alert" className="meeting-auth-error">{error}</p>}<button className="meeting-google" disabled={!consent||busy||sent} onClick={()=>void go('google')}><GoogleMark/>Googleで登録</button><div className="meeting-auth-divider">またはメールで</div><form onSubmit={e=>{e.preventDefault();void go(sent?'verify':'request');}}><label>メールアドレス<input type="email" autoComplete="email" maxLength={254} required value={email} disabled={sent||busy} onChange={e=>setEmail(e.target.value)}/></label>{sent&&<label>メールに届いた6桁のコード<input inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} required value={code} onChange={e=>setCode(e.target.value.replace(/[^0-9]/g,''))}/></label>}<button className="meeting-submit" disabled={busy||!consent}>{busy?'確認中…':sent?'認証して登録':'メールで登録'}</button>{sent&&<div className="meeting-auth-actions"><button type="button" onClick={()=>{setSent(false);setCode('');}}>入力内容を変更</button><button type="button" disabled={busy} onClick={()=>void go('request')}>コードを再送</button></div>}</form><p className="meeting-auth-legal">登録済みの方は同じアカウントで進めます。<a href="/login/member">ログインはこちら</a></p></section></main>;
}
