'use client';
import {useEffect,useState} from 'react';
import type {Meeting,RosterPerson} from './types';
import {GoogleMark} from '@/app/login/LoginForm';
const empty={name:'',company:'',industry:'',services:'',area:'',table:''};
export default function MeetingSignup({event,requests=false,signedIn=false}:{event:Meeting;requests?:boolean;signedIn?:boolean}) {
 const [email,setEmail]=useState(''),[code,setCode]=useState(''),[sent,setSent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 const [people,setPeople]=useState<Pick<RosterPerson,'id'|'name'|'company'>[]>([]),[rosterId,setRosterId]=useState(''),[profile,setProfile]=useState(empty),[walkIn,setWalkIn]=useState(false),[consent,setConsent]=useState(false);
 const back=`/meeting/${event.id}${requests?'/requests':''}`,api=`/api/meeting/${event.id}/account`;
 useEffect(()=>{
  const receipt=window.location.hash.match(/^#receipt=([a-f0-9]{64})$/)?.[1];if(receipt){try{localStorage.setItem(`tasuki-meeting-${event.id}`,receipt);}catch{}}
  if(new URLSearchParams(window.location.search).has('login'))setError('認証できませんでした。会社情報を確認してもう一度進むか、メールをご利用ください。');
  let alive=true;fetch(api+'?people=1',{cache:'no-store'}).then(async r=>{const d=await r.json() as {people:typeof people;error?:string};if(!r.ok)throw new Error(d.error);if(alive)setPeople(d.people);}).catch(e=>{if(alive)setError(e.message);}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};
 },[event.id,api]);
 async function choose(id:string){setRosterId(id);setConsent(false);setProfile(empty);if(!id)return;setBusy(true);setError('');try{const r=await fetch(api+'?rosterId='+encodeURIComponent(id),{cache:'no-store'}),d=await r.json() as {person:RosterPerson;error?:string};if(!r.ok)throw new Error(d.error);setProfile(d.person);}catch(e){setError(e instanceof Error?e.message:'名簿を読み込めませんでした。');setRosterId('');}finally{setBusy(false);}}
 async function post(action:string){const r=await fetch(api,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,email,code,rosterId,profile,walkIn,consent})}),d=await r.json() as {error?:string;draft?:string};if(!r.ok)throw new Error(d.error||'登録できませんでした。');return d;}
 async function proceed(action:string){setBusy(true);setError('');try{if(!consent)throw new Error('ご本人の会社情報と利用規約への同意を確認してください。');if(action==='google'){const d=await post('draft');window.location.href=`/api/auth/google/start?meeting=${encodeURIComponent(event.id)}&draft=${encodeURIComponent(d.draft||'')}&return_to=${encodeURIComponent(back)}`;}else{await post(action);if(action==='request')setSent(true);else window.location.reload();}}catch(e){setError(e instanceof Error?e.message:'もう一度お試しください。');}finally{setBusy(false);}}
 return <main className="meeting-page meeting-survey meeting-signup"><header className="meeting-hiru-brand"><strong>ひるのめぐろ</strong><small>Powered by TASUKI</small></header><p className="meeting-auth-event">{event.title}</p><h1>今日の出会いを、<br/>仕事につなげる。</h1><section className="meeting-signup-form"><h2>{signedIn?'会社情報を確認して進む':'かんたん登録で、アンケートへ'}</h2><p>会社を選ぶと、事業内容が自動で入ります。</p>
 <fieldset disabled={busy||sent} className="meeting-registration-profile">{!walkIn?<><label htmlFor="signup-company">会社名・ご本人のお名前<select id="signup-company" value={rosterId} disabled={loading||busy} onChange={e=>void choose(e.target.value)}><option value="">{loading?'名簿を読み込んでいます…':'ご自身の会社・お名前を選んでください'}</option>{people.map(p=><option key={p.id} value={p.id}>{p.company} ／ {p.name}</option>)}</select></label><button className="meeting-registration-switch" type="button" onClick={()=>{setWalkIn(true);setRosterId('');setProfile(empty);setConsent(false);}}>名簿にない方はこちら</button></>:<><p className="meeting-help">当日参加の方は会社情報を入力してください。</p><label>お名前<input value={profile.name} maxLength={120} onChange={e=>setProfile({...profile,name:e.target.value})}/></label><label>会社名・屋号<input value={profile.company} maxLength={120} onChange={e=>setProfile({...profile,company:e.target.value})}/></label><button className="meeting-registration-switch" type="button" onClick={()=>{setWalkIn(false);setProfile(empty);setConsent(false);}}>名簿から選ぶ</button></>}
 {(rosterId||walkIn)&&<><label>事業概要・会社PR<textarea rows={2} maxLength={500} value={profile.services} onChange={e=>setProfile({...profile,services:e.target.value})} placeholder="例：チラシのデザイン・印刷"/></label><details className="meeting-profile-details"><summary>会社情報を確認・修正する</summary>{!walkIn&&<><label>お名前<input maxLength={120} value={profile.name} onChange={e=>setProfile({...profile,name:e.target.value})}/></label><label>会社名<input maxLength={120} value={profile.company} onChange={e=>setProfile({...profile,company:e.target.value})}/></label></>}<label>業種<input maxLength={120} value={profile.industry} onChange={e=>setProfile({...profile,industry:e.target.value})}/></label><label>対応地域<input maxLength={120} value={profile.area} onChange={e=>setProfile({...profile,area:e.target.value})}/></label></details></>}
 <label className="meeting-consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>ご本人の会社情報です。この情報をTASUKIの会員情報として保存し、<a href="/terms" target="_blank">利用規約</a>・<a href="/privacy" target="_blank">プライバシーポリシー</a>に同意して進みます。</span></label></fieldset>
 {error&&<p role="alert" className="meeting-auth-error">{error}</p>}
 {signedIn?<button className="meeting-submit" disabled={busy||!consent} onClick={()=>void proceed('profile')}>この情報でアンケートへ</button>:<><button className="meeting-google" disabled={busy||sent||!consent} onClick={()=>void proceed('google')}><GoogleMark/>Googleで進む</button><div className="meeting-auth-divider">またはメールで</div><form onSubmit={e=>{e.preventDefault();void proceed(sent?'verify':'request');}}><label htmlFor="meeting-email">メールアドレス</label><input id="meeting-email" type="email" autoComplete="email" required maxLength={254} value={email} disabled={sent||busy} onChange={e=>setEmail(e.target.value)}/>{sent&&<><label htmlFor="meeting-code">メールに届いた6桁のコード</label><input id="meeting-code" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} required value={code} onChange={e=>setCode(e.target.value.replace(/[^0-9]/g,''))}/><p className="meeting-help">コードの有効期限は10分です。</p></>}
 <button className="meeting-submit" disabled={busy||!consent}>{busy?'確認中…':sent?'認証してアンケートへ':'メールで進む'}</button>{sent&&<div className="meeting-auth-actions"><button type="button" disabled={busy} onClick={()=>{setSent(false);setCode('');setError('');}}>メール・会社情報を変更</button><button type="button" disabled={busy} onClick={()=>void proceed('request')}>コードを再送</button></div>}</form></>}
 <p className="meeting-auth-legal">初めての方は、認証するとTASUKIの無料アカウントが作成されます。登録後はそのままアンケートへ。例会のあとも同じアカウントを使えます。</p></section></main>;
}
