'use client';
import { useEffect,useState } from 'react';
import type { Preparation } from '@/db/meeting-automation';
type Status={venueName?:string;website?:string;startTime?:string;enabled:boolean;minutes:number;tables:number;connected:boolean;checkedAt:number;error:string;plans:Preparation[]};
const labels:Record<string,string>={scheduled:'作成予定',ready:'準備完了',roster_pending:'名簿の準備待ち',schedule_changed:'開催日要確認',cancelled:'削除済み'};
export default function AutomationPanel({venueId='hirunomeguro',onCreated,onOpenMeeting}:{venueId?:string;onCreated:()=>void;onOpenMeeting?:(id:string,view?:string)=>void}){
 const [data,setData]=useState<Status|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function request(body?:Record<string,unknown>){setBusy(true);setError('');try{const r=await fetch('/api/admin/meetings/automation?venue='+encodeURIComponent(venueId),body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,venueId})}:{cache:'no-store'});const d=await r.json() as Status & {error?:string};if(!r.ok)throw new Error(d.error);setData(d);if(body?.action==='prepare')onCreated();return true;}catch(e){setError(e instanceof Error?e.message:'読み込めませんでした。');return false;}finally{setBusy(false);}}
 useEffect(()=>{fetch('/api/admin/meetings/automation?venue='+encodeURIComponent(venueId),{cache:'no-store'}).then(async r=>{const d=await r.json() as Status;if(!r.ok)throw new Error('読み込めませんでした。');setData(d);}).catch(e=>setError(e.message));},[venueId]);
 return <section className="meeting-automation"><div className="meeting-automation-heading"><div><small>{data?.venueName||'会場'}</small><h2>例会の準備を自動で</h2></div><span className="meeting-auto-status">{!data?'読み込み中…':data.enabled?'毎日 1:00 に確認':'自動作成は停止中'}</span></div><p>開催2日前にアンケートを作成。まちださがみ形式の名簿を反映し、テーブル用QRを用意します。</p>
 {error&&<p role="alert" className="meeting-error">{error}</p>}{data?.error&&<p className="meeting-error">{data.error}</p>}
 {data&&<><details><summary>自動準備の設定 · とみざわ{data.connected?'接続設定済み':'未接続'}</summary><form onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const f=new FormData(form);const saved=await request({action:'save',enabled:f.get('enabled')==='on',minutes:Number(f.get('minutes')),tables:Number(f.get('tables')),loginUrl:f.get('loginUrl')});if(saved)(form.elements.namedItem('loginUrl') as HTMLInputElement).value='';}}><label className="meeting-consent"><input name="enabled" type="checkbox" defaultChecked={data.enabled}/><span>開催2日前の自動作成を有効にする</span></label><label>回答締切（{data.startTime||'11:30'}の開始から何分後）<input name="minutes" type="number" min="0" max="180" defaultValue={data.minutes} required/><small>15分なら開始15分後に締切。作成済みの例会は、各例会の「受付・締切」で調整できます。</small></label><label>名簿のテーブル数が未確定の場合<input name="tables" type="number" min="1" max="60" defaultValue={data.tables} required/></label><label>とみざわの簡単ログインURL<input name="loginUrl" type="password" autoComplete="off" placeholder={data.connected?'変更する場合だけ入力':'管理メニュー「簡単ログインURL」のURL'}/></label><small>接続情報は暗号化して保存します。席割り・名簿ロックは変更しません。名簿未作成の場合は作成後に再実行してください。</small><button disabled={busy}>設定を保存</button></form></details>
 <div className="meeting-admin-tools"><button className="meeting-secondary" disabled={busy} onClick={()=>void request({action:'sync'})}>ホームページの開催日を読み込む</button></div>
 <div className="meeting-plans">{data.plans.map(p=><article key={p.key}><div><b>{p.title}</b><small>自動準備：{new Date(p.prepareAt).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'})}</small><span>{labels[p.status]??p.status}</span>{p.error&&<p className="meeting-error">{p.error}</p>}</div><div className="meeting-plan-actions">{p.meetingId&&<><button className="meeting-secondary" onClick={()=>onOpenMeeting?.(p.meetingId!)}>この例会を編集</button><button className="meeting-secondary" onClick={()=>onOpenMeeting?.(p.meetingId!,'qr')}>QR印刷</button></>}<button disabled={busy||p.status==='ready'||p.status==='cancelled'} className="meeting-secondary" onClick={()=>void request({action:'prepare',key:p.key})}>{p.status==='cancelled'?'削除済み':p.meetingId?'準備を再実行':'今すぐ準備'}</button></div></article>)}</div>
 <small>開催日：<a href={data.website} target="_blank" rel="noreferrer">{data.venueName}ホームページ</a>{data.checkedAt?` · 最終確認 ${new Date(data.checkedAt).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'})}`:''}</small></>}
 </section>;
}
