'use client';
import {DEFAULT_MEETING_VENUE} from '@/app/meeting/venue-types';
import {useEffect,useState} from 'react';
import type {MeetingVenue} from '@/app/meeting/venue-types';
import type {MeetingSummary} from '@/db/meetings';
type Payload={error?:string;venues:MeetingVenue[];platform:boolean;summaries:MeetingSummary[]};
import MeetingAdmin from './MeetingAdmin';
import VenueSettings from './VenueSettings';
export default function MeetingWorkspace({initialEventId='',initialView='',onUpdated}:{initialEventId?:string;initialView?:string;onUpdated?:()=>void}){
 const [now,setNow]=useState(0);
 const [venues,setVenues]=useState<MeetingVenue[]>([]),[venueId,setVenueId]=useState(''),[platform,setPlatform]=useState(false),[settings,setSettings]=useState(false),[events,setEvents]=useState<MeetingSummary[]>([]),[editor,setEditor]=useState(!!initialEventId||!!initialView),[eventId,setEventId]=useState(initialEventId),[view,setView]=useState(initialView),[error,setError]=useState(''),[busy,setBusy]=useState(false),[deleting,setDeleting]=useState<MeetingSummary|null>(null);
 const venue=venues.find(v=>v.id===venueId);
 async function loadVenues(preferred?:string){const r=await fetch('/api/admin/meeting-venues',{cache:'no-store'}),d=await r.json() as Payload;if(!r.ok)throw new Error(d.error||'会場を読み込めませんでした。');setVenues(d.venues);setPlatform(d.platform);const selected=d.venues.find((v:MeetingVenue)=>v.id===preferred&&v.enabled)||d.venues.find((v:MeetingVenue)=>v.enabled);if(selected)setVenueId(selected.id);}
 useEffect(()=>{let alive=true;const preferred=new URLSearchParams(location.search).get('venue');fetch('/api/admin/meeting-venues',{cache:'no-store'}).then(async r=>{const d=await r.json() as Payload;if(!r.ok)throw new Error(d.error);let eventVenue='';if(initialEventId){const detail=await fetch('/api/admin/meetings?id='+encodeURIComponent(initialEventId),{cache:'no-store'});if(detail.ok)eventVenue=(await detail.json() as {event:{venueId:string}}).event.venueId;}if(!alive)return;setVenues(d.venues);setPlatform(d.platform);const selected=d.venues.find(v=>v.id===(eventVenue||preferred)&&v.enabled)||d.venues.find(v=>v.enabled);if(selected)setVenueId(selected.id);}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[initialEventId]);
 useEffect(()=>{const start=setTimeout(()=>setNow(Date.now()),0),timer=setInterval(()=>setNow(Date.now()),15000);return()=>{clearTimeout(start);clearInterval(timer);};},[]);
 async function load(){if(!venueId)return;const r=await fetch('/api/admin/meetings?venue='+encodeURIComponent(venueId),{cache:'no-store'}),d=await r.json() as Payload;if(!r.ok)throw new Error(d.error||'例会を読み込めませんでした。');setEvents(d.summaries);onUpdated?.();}
 useEffect(()=>{let alive=true;if(!venueId)return;fetch('/api/admin/meetings?venue='+encodeURIComponent(venueId),{cache:'no-store'}).then(async r=>{const d=await r.json() as Payload;if(!r.ok)throw new Error(d.error);if(alive)setEvents(d.summaries);}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[venueId]);
 function changeVenue(id:string){setEvents([]);setVenueId(id);setEditor(false);setEventId('');setSettings(false);setError('');const u=new URL(location.href);u.searchParams.set('venue',id);u.searchParams.set('tab','surveys');u.searchParams.delete('event');u.searchParams.delete('view');history.replaceState(null,'',u);}
 function open(id='',mode='edit'){setEditor(true);setEventId(id);setView(mode);const u=new URL(location.href);u.searchParams.set('tab','surveys');u.searchParams.set('venue',venueId);if(id)u.searchParams.set('event',id);else u.searchParams.delete('event');u.searchParams.set('view',mode);history.replaceState(null,'',u);}
 function close(){setEditor(false);const u=new URL(location.href);u.searchParams.delete('event');u.searchParams.delete('view');history.replaceState(null,'',u);void load().catch(e=>setError(e.message));}
 async function remove(){if(!deleting||busy)return;setBusy(true);setError('');try{const r=await fetch('/api/admin/meetings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'delete',id:deleting.id,confirmation:deleting.title})}),d=await r.json() as Payload;if(!r.ok)throw new Error(d.error);setDeleting(null);await load();}catch(e){setError(e instanceof Error?e.message:'削除できませんでした。');}finally{setBusy(false);}}
 return <section className="meeting-workspace"><div className="meeting-workspace-toolbar"><label>管理する会場<select aria-label="管理する会場" value={venueId} onChange={e=>changeVenue(e.target.value)}>{venues.filter(v=>v.enabled).map(v=><option value={v.id} key={v.id}>{v.name}</option>)}</select></label><button className="meeting-secondary" disabled={busy} onClick={()=>void load().catch(e=>setError(e.message))}>例会を再読み込み</button>{platform&&<button className="meeting-secondary" onClick={()=>setSettings(!settings)}>{settings?'会場設定を閉じる':'会場設定・担当者'}</button>}</div>
 {error&&!deleting&&<p role="alert" className="meeting-error">{error}</p>}
 {platform&&settings&&venue&&<VenueSettings key={venue.id} venue={venue} onSaved={async id=>{await loadVenues(id);changeVenue(id);}}/>}
 {venue&&(editor?<MeetingAdmin key={venue.id+eventId+view} embedded venueId={venue.id} venueName={venue.name} initialEventId={eventId} initialView={view} onClose={close} onUpdated={()=>void load().catch(e=>setError(e.message))}/>:<>
 <div className="admin-meeting-heading"><div><h2>{venue.name}の例会</h2><p>準備から結果公開まで、ここで管理できます。</p></div><button onClick={()=>open('','preparation')}>{venue.id===DEFAULT_MEETING_VENUE?'＋ 作成・自動準備':'＋ 例会を作成'}</button></div>
 <div className="meeting-operation-guide" aria-label="例会運営の流れ">{['名簿・QRを準備','来場・回答を確認','締切後に集計','候補を確認・公開'].map((text,i)=><span key={text}><b>{i+1}</b>{text}</span>)}</div>
 {!events.length&&<p className="admin-empty">まだイベントがありません。上の作成ボタンから始めてください。</p>}
 <div className="admin-meeting-grid">{events.map(event=>{const state=event.state==='open'?(now>=event.closesAt?'受付終了':'受付中'):({analyzing:'分析中',review:'候補確認中',published:'結果公開済み'} as const)[event.state];return <article className="admin-meeting-card" key={event.id}>
 <div className="admin-row-top"><span className="admin-meeting-venue">{event.venue}</span><span className={`admin-state ${state==='受付中'||event.state==='published'?'is-on':'is-new'}`}>{state}</span></div>
 <h3><button className="admin-meeting-title-button" onClick={()=>open(event.id)}>{event.title}</button></h3><p className="admin-meeting-deadline">回答締切 {new Date(event.closesAt).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo',year:'numeric',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})}</p>
 <dl className="admin-meeting-stats"><div><dt>名簿</dt><dd>{event.rosterCount??0}<small>人</small></dd></div><div><dt>回答</dt><dd>{event.answerCount}<small>人</small></dd></div><div><dt>出席確認</dt><dd>{event.presentCount}<small>人</small></dd></div></dl>
 <div className="meeting-event-progress">{!event.rosterCount?'名簿の取込から始めてください。':event.state==='published'?`紹介候補あり ${event.matchedCount}人 ／ 希望を記入した出席者 ${event.needCount}人`:event.state==='review'?'全員の分析が完了しました。候補を確認して公開できます。':event.state==='analyzing'?`分析済み ${event.analyzedCount} ／ ${event.presentCount}人`:now>=event.closesAt?'受付は終了しました。出席確認後、集計を開始してください。':'QRを配布し、回答と出席を確認してください。'}</div>
 <p className="meeting-registration-count">会社情報を登録済み：{event.registeredCount}人 <small>※既存アカウントを含む</small></p>
 <div className="admin-meeting-links"><button className="admin-meeting-manage" onClick={()=>open(event.id)}>編集 →</button><button onClick={()=>open(event.id,'answer')}>回答画面を確認</button><button onClick={()=>open(event.id,'qr')}>QR印刷</button><button className="admin-meeting-delete" onClick={()=>{setError('');setDeleting(event);}}>削除</button></div></article>;})}</div>
 </>)}
 {deleting&&<div className="admin-confirm-backdrop"><div className="admin-confirm" role="dialog" aria-modal="true" aria-labelledby="meeting-workspace-delete"><h2 id="meeting-workspace-delete">このイベントを削除しますか？</h2><p><b>{deleting.title}</b></p><p>名簿 {deleting.rosterCount??0}人・回答 {deleting.answerCount}人と紹介結果を削除します。共有済みのURL・QRは使えなくなります。元に戻せません。</p><p>TASUKIの会員アカウントと他のイベントは残ります。</p>{error&&<p role="alert" className="meeting-error">{error}</p>}<button className="is-danger" disabled={busy} onClick={()=>void remove()}>{busy?'削除中…':'このイベントを削除'}</button><button autoFocus className="meeting-secondary" disabled={busy} onClick={()=>{setDeleting(null);setError('');}}>キャンセル</button></div></div>}
 </section>;
}
