'use client';
import {useEffect,useState} from 'react';
import type {TrashedMeeting} from '@/db/meeting-management';
export default function MeetingTrash({venueId,venueName,onClose,onUpdated}:{venueId:string;venueName:string;onClose:()=>void;onUpdated:()=>void}){
 const [events,setEvents]=useState<TrashedMeeting[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[confirm,setConfirm]=useState(false);
 async function load(){const r=await fetch('/api/admin/meetings?trash=1&venue='+encodeURIComponent(venueId),{cache:'no-store'}),d=await r.json() as {trash:TrashedMeeting[];error?:string};if(!r.ok)throw new Error(d.error);setEvents(d.trash);}
 useEffect(()=>{let alive=true;fetch('/api/admin/meetings?trash=1&venue='+encodeURIComponent(venueId),{cache:'no-store'}).then(async r=>{const d=await r.json() as {trash:TrashedMeeting[];error?:string};if(!r.ok)throw new Error(d.error);if(alive)setEvents(d.trash);}).catch(e=>{if(alive)setError(e.message);}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[venueId]);
 async function act(action:string,id?:string){setBusy(true);setError('');try{const r=await fetch('/api/admin/meetings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,venueId,id,confirmation:action==='empty-trash'?'ゴミ箱を空にする':undefined})}),d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error);setConfirm(false);await load();onUpdated();}catch(e){setError(e instanceof Error?e.message:'処理できませんでした。');}finally{setBusy(false);}}
 return <section className="meeting-trash"><button className="meeting-secondary" onClick={onClose}>← 例会アンケート一覧</button><div className="admin-meeting-heading"><div><h2>{venueName}のゴミ箱 <small>{events.length}件</small></h2><p>削除したイベントは、名簿・回答・紹介結果ごと復元できます。ゴミ箱にある間は、参加者用のURL・QRは利用できません。</p></div><button className="admin-meeting-delete" disabled={busy||loading||!events.length} onClick={()=>setConfirm(true)}>ゴミ箱を空にする</button></div>{error&&!confirm&&<p className="meeting-error" role="alert">{error}</p>}
 {loading?<p role="status">ゴミ箱を読み込んでいます…</p>:!events.length?<p className="admin-empty">ゴミ箱は空です。</p>:<div className="admin-meeting-grid">{events.map(e=><article className="admin-meeting-card" key={e.id}><div className="admin-row-top"><span>{e.venue}</span><span className="admin-state is-new">ゴミ箱</span></div><h3>{e.title}</h3><p>削除日時 {new Date(e.deletedAt).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'})}</p><dl className="admin-meeting-stats"><div><dt>名簿</dt><dd>{e.rosterCount}<small>人</small></dd></div><div><dt>回答</dt><dd>{e.answerCount}<small>人</small></dd></div></dl><p className="meeting-help">元の回答締切 {new Date(e.closesAt).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'})}。復元しても締切は変わりません。</p><button className="admin-meeting-manage" disabled={busy} onClick={()=>void act('restore',e.id)}>イベントを復元</button></article>)}</div>}
 {confirm&&<div className="admin-confirm-backdrop"><div className="admin-confirm" role="dialog" aria-modal="true" aria-labelledby="empty-meeting-trash"><h2 id="empty-meeting-trash">ゴミ箱を空にしますか？</h2><p>{venueName}のゴミ箱にあるイベントと名簿・回答・紹介結果を完全に削除します。元に戻せません。</p><p>TASUKIの会員アカウントと、ゴミ箱以外のイベントは残ります。</p>{error&&<p role="alert" className="meeting-error">{error}</p>}<button className="is-danger" disabled={busy} onClick={()=>void act('empty-trash')}>{busy?'完全削除中…':'ゴミ箱を空にする'}</button><button autoFocus className="meeting-secondary" disabled={busy} onClick={()=>{setConfirm(false);setError('');}}>キャンセル</button></div></div>}
 </section>;
}
