'use client';
import {useEffect,useState} from 'react';
type Payload={error?:string;operators:MeetingOperator[];id:string};
import type {MeetingVenue,MeetingOperator} from '@/app/meeting/venue-types';
export default function VenueSettings({venue,onSaved}:{venue:MeetingVenue;onSaved:(id:string)=>Promise<void>}){
 const [operators,setOperators]=useState<MeetingOperator[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[note,setNote]=useState('');
 async function load(){const r=await fetch('/api/admin/meeting-venues?id='+encodeURIComponent(venue.id),{cache:'no-store'});if(!r.ok)throw new Error('担当者を読み込めませんでした。');setOperators((await r.json() as Payload).operators);}
 useEffect(()=>{let alive=true;fetch('/api/admin/meeting-venues?id='+encodeURIComponent(venue.id),{cache:'no-store'}).then(async r=>{if(!r.ok)throw new Error('担当者を読み込めませんでした。');const d=await r.json() as Payload;if(alive)setOperators(d.operators);}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[venue.id]);
 async function post(body:Record<string,unknown>){setBusy(true);setError('');setNote('');try{const r=await fetch('/api/admin/meeting-venues',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json() as Payload;if(!r.ok)throw new Error(d.error);if(body.action==='operator'){await load();setNote('担当者の権限を更新しました。');}else await onSaved(d.id);}catch(e){setError(e instanceof Error?e.message:'保存できませんでした。');}finally{setBusy(false);}}
 function fields(v?:MeetingVenue){return <><label>会場名<input name="name" maxLength={120} defaultValue={v?.name} required placeholder="例：ひるのめぐろ"/></label><label>ホームページURL<input name="website" type="url" defaultValue={v?.website} placeholder="https://…"/></label><label>とみざわの会場識別子<input name="legacySlug" defaultValue={v?.legacySlug} pattern="[a-z0-9_-]+" placeholder="例：hirunomeguro"/><small>とみざわURLの「shuseiclub.jp/」直後の文字です。接続先をこの会場に限定します。</small></label><label>例会開始時刻（日本時間）<input name="startTime" type="time" defaultValue={v?.startTime||'11:30'} required/></label></>;}
 async function save(e:React.FormEvent<HTMLFormElement>,id?:string){e.preventDefault();const f=new FormData(e.currentTarget);await post({action:'save',...(id?{id}:{}),name:f.get('name'),website:f.get('website'),legacySlug:f.get('legacySlug'),startTime:f.get('startTime')});}
 return <section className="meeting-admin-section meeting-venue-settings"><h2>会場設定・担当者</h2><p className="meeting-help">会場の担当者には、この会場の例会だけを表示します。TASUKIの会員・投稿や他会場の回答は管理できません。</p>{error&&<p role="alert" className="meeting-error">{error}</p>}{note&&<p role="status">{note}</p>}
 <details><summary>{venue.name}の設定</summary><form onSubmit={e=>void save(e,venue.id)}><div className="meeting-venue-fields">{fields(venue)}</div><button disabled={busy}>会場設定を保存</button></form></details>
 <details><summary>担当者のアクセス権限</summary><p className="meeting-help">担当者は、このメールアドレスでGoogleまたはメール認証にログインして /admin を開きます。</p><ul>{operators.map(o=><li key={o.email}><span>{o.email}</span><button className="meeting-secondary" disabled={busy} onClick={()=>void post({action:'operator',id:venue.id,email:o.email,enabled:false})}>担当から外す</button></li>)}</ul><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void post({action:'operator',id:venue.id,email:f.get('email'),enabled:true});}}><label>担当者のメールアドレス<input type="email" name="email" required maxLength={254} placeholder="担当者の登録メールアドレス"/></label><button disabled={busy}>この会場の担当者に追加</button></form></details>
 <details><summary>他会場を追加する</summary><p className="meeting-help">追加した会場は別の名簿・回答・接続情報で運用します。自動作成は設定するまで停止しています。</p><form onSubmit={e=>void save(e)}><div className="meeting-venue-fields">{fields()}</div><button disabled={busy}>会場を作成</button></form></details>
 </section>;
}
